name: Atualização Automática do db.json

on:
  push:
    branches:
      - main

jobs:
  atualizar-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar Dependências
        run: npm install

      - name: Executar Script de Atualização
        run: curl -X GET https://cooklator-backend.onrender.com/atualizar-db

      - name: Commit e Push Atualizações
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Atualização automática do db.json"
          git remote set-url origin "https://${{ secrets.GH_TOKEN }}@github.com/Juudm/backend-cooklator"
          git push origin main
